### ISSUE TITLE
TTY device names under /dev for USART6 and RS-485

### ISSUE THREAD

**Issue by mgrouch** [m5stack/CoreMP135_buildroot-external-st#6]
What are try device names under /dev for USART6 and RS-485?

can that be added to the documentation somewhere?

thanks

**Comment by dianjixz** [comment]
Thank you very much for your valuable feedback. The document team has been notified to add descriptions of the relevant pins in Linux. Please stay tuned for updates on the [CoreMP135](https://docs.m5stack.com/en/core/M5CoreMP135) official website.

**Comment by mgrouch** [comment]
The request wasn’t about pins. 
it was about device names on Debian image. 

/dev/tty???

How usart6 and rs485 are named under 

/dev/  filesystem?

thanks

**Comment by dianjixz** [comment]
yes,i see.The [CoreMP135](https://docs.m5stack.com/en/core/M5CoreMP135) document has been updated.

**Comment by mgrouch** [comment]
Ok. 

So it’s 

/dev/ttySTM0 for usart6

and 

/dev/ttySTM3 for Rs-485

thanks
