### ISSUE TITLE
Reboot command doesn't reboot if I plug HDMI and keyboard without serial console

### ISSUE THREAD

**Issue by mgrouch** [m5stack/CoreMP135_buildroot-external-st#8]
Reboot command doesn't reboot if I plug HDMI screen and keyboard without serial console.
If I plug USB-C to a computer then reboot command works.

Thanks

**Comment by mgrouch** [comment]
Steps to reproduce:

Boot it up without USB-C plugged in. (Connected to HDMI and keyboard)
Login.
Type reboot command on keyboard and hit enter
It will sit with blinking cursor in upper left corner of HDMI screen indefinitely.
Plugin coremp135 into another computer via USB-C on coremp135.
Reboot will happen

**Comment by dianjixz** [comment]
This is a bug in the g_serial module. When the g_serial module is loaded but not working with USB, it cannot be forcibly unmounted. You can remove the libcomposite and g_serial modules from /etc/modules, and then add the command `modprobe libcomposite; modprobe g_serial;` to /etc/rc.local to enable the OTG USB serial terminal at startup. This issue will be fixed in upcoming system updates.

**Comment by mgrouch** [comment]
> This is a bug in the g_serial module. When the g_serial module is loaded but not working with USB, it cannot be forcibly unmounted. You can remove the libcomposite and g_serial modules from /etc/modules, and then add the command `modprobe libcomposite; modprobe g_serial;` to /etc/rc.local to enable the OTG USB serial terminal at startup. This issue will be fixed in upcoming system updates.

I did these changes but it didn’t fix the issue

Thanks

**Comment by dianjixz** [comment]
Adjust patch [commit](https://github.com/m5stack/CoreMP135_buildroot-external-st/commit/2ac8f7a4532159adfa4858569a18f0e11594b118)

**Comment by dianjixz** [comment]
@mgrouch The BBN system is unfamiliar to me, and I have many planned tasks ahead. Perhaps BBN-related tasks will be scheduled later, but not now. Could you please specify some particular issues you are facing so I can help you resolve them?

**Comment by mgrouch** [comment]
@dianjixz 

I've incorporated your changes for reboot. And it's now working for me. I have only one issue to resolve with built-in LCD blanking and waking up on touch
